# Generated by Django 3.1.1 on 2020-11-19 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Seller_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=80)),
                ('car_model', models.CharField(max_length=80)),
                ('car_year', models.CharField(max_length=80)),
                ('car_speed', models.DecimalField(decimal_places=2, max_digits=7)),
                ('car_owner_location', models.CharField(max_length=80)),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('car_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('car_description', models.TextField(blank=True, default='', null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('car_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.car')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.category')),
            ],
        ),
        migrations.CreateModel(
            name='User_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_plan_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.plan')),
            ],
        ),
        migrations.DeleteModel(
            name='Homepage',
        ),
    ]
